CREATE TABLE CHILD(
	CHILD_ID INTEGER UNSIGNED AUTO_INCREMENT,
    CHILD_FNAME VARCHAR(255) NOT NULL,
    CHILD_LNAME VARCHAR(255) NOT NULL,
    CHILD_AGE INTEGER NOT NULL,
    CLASS_ID INTEGER UNSIGNED,
    PRIMARY KEY (CHILD_ID),
    FOREIGN KEY (CLASS_ID) REFERENCES CLASSROOM (CLASS_ID) ON UPDATE CASCADE
);

SELECT * FROM CHILD;

-- Show # of students for each classroom
SELECT c.CLASS_ID, c.CLASS_NAME, c.CLASS_CAPACITY, c.FACILITY_ID, (SELECT COUNT(*) 
																	FROM CHILD ch 
																	WHERE ch.CLASS_ID = c.CLASS_ID) AS NUM_STUDENTS
FROM CLASSROOM c;

-- Class 1
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Emanuel', 'Meadows', 7, 1);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Bernard', 'Clements', 7, 1);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Cheyanne', 'Moses', 7, 1);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Camren', 'Bridges', 7, 1);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Lamont', 'Rowland', 6, 1);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Jaslyn', 'Harrison', 7, 1);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Ruben', 'Blackburn', 7, 1);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Kimberly', 'Garcia', 6, 1);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Rene', 'Hubbard', 7, 1);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Monica', 'Ayala', 6, 1);

-- Class 2
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Christopher', 'Chang', 5, 2);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Melany', 'Burton', 6, 2);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Dominik', 'Ramsey', 5, 2);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Colby', 'Norris', 7, 2);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Kaydence', 'Fry', 5, 2);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Scarlett', 'Boyle', 7, 2);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Justice', 'Salazar', 5, 2);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Konnor', 'Reed', 7, 2);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Ariella', 'Fletcher', 7, 2);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Cali', 'Fry', 7, 2);

-- Class 3
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Caleb', 'Hunter', 7, 3);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Mohamed', 'Huffman', 7, 3);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Tess', 'Sullivan', 5, 3);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Evelin', 'Brady', 6, 3);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Nathan', 'Lucas', 7, 3);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Valerie', 'Garcia', 6, 3);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Tristan', 'Watts', 6, 3);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Eden', 'Hines', 7, 3);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Lorena', 'Stafford', 5, 3);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Scott', 'Zhang', 6, 3);

-- Class 4
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Abram', 'Barker', 7, 4);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Jovanni', 'Hickman', 7, 4);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Arielle', 'Hawkins', 6, 4);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Valerie', 'Blackwell', 5, 4);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Matthias', 'Munoz', 7, 4);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Zavier', 'Preston', 5, 4);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Eden', 'Hanna', 6, 4);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Londyn', 'Adams', 7, 4);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Kara', 'Noble', 7, 4);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Nick', 'Mora', 6, 4);

-- Class 5
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Alondra', 'Trujillo', 6, 5);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Zaiden', 'Summers', 5, 5);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Chase', 'Owens', 5, 5);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Avery', 'Compton', 6, 5);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Darius', 'Herring', 7, 5);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Danika', 'Villarreal', 6, 5);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Aileen', 'Velez', 7, 5);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Jamie', 'Bennett', 5, 5);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Trevor', 'Snow', 5, 5);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Kiersten', 'Dawson', 5, 5);

-- Class 6
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Sophie', 'Shields', 6, 6);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Savion', 'Aguilar', 7, 6);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('John', 'Anthony', 6, 6);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Fiona', 'Lewis', 6, 6);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Jaylene', 'Rich', 7, 6);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Braedon', 'Mcbride', 7, 6);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Raiden', 'Washington', 7, 6);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Felipe', 'Crawford', 7, 6);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Jaiden', 'Mcguire', 5, 6);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Adan', 'Espinoza', 6, 6);

-- Class 7
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Albert', 'Blackwell', 6, 7);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Mark', 'Lam', 6, 7);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Ellis', 'Dickson', 5, 7);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Jace', 'Vega', 6, 7);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Matthias', 'Watkins', 7, 7);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Jasmin', 'Arellano', 6, 7);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Phoenix', 'Hunt', 7, 7);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Abdiel', 'Reid', 5, 7);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Kenny', 'Landry', 6, 7);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Edward', 'Reese', 7, 7);

-- Class 8
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Reece', 'Wiley', 5, 8);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Summer', 'Pearson', 5, 8);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Houston', 'Barr', 6, 8);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Maximillian', 'Hall', 5, 8);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Samara', 'Henderson', 7, 8);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Kylan', 'Kennedy', 5, 8);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Nina', 'Avery', 6, 8);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Jerome', 'Frye', 7, 8);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Helena', 'Simmons', 5, 8);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Slade', 'Mcgrath', 5, 8);

-- Class 9
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Xiomara', 'Proctor', 6, 9);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Maya', 'Moon', 6, 9);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Reese', 'Dawson', 6, 9);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Ismael', 'Campbell', 7, 9);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Graham', 'Salas', 6, 9);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Emilie', 'Townsend', 7, 9);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Jaylan', 'Obrien', 5, 9);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Jewel', 'Berger', 5, 9);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Shania', 'Horn', 6, 9);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Efrain', 'Sherman', 5, 9);

-- Class 10
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Felix', 'Knox', 7, 10);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Cindy', 'Whitney', 7, 10);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Maeve', 'Marsh', 7, 10);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Aisha', 'Davenport', 5, 10);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Melissa', 'Valenzuela', 6, 10);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Jan', 'Bray', 5, 10);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Aryan', 'Sampson', 5, 10);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Kayden', 'Huang', 6, 10);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Judah', 'Jackson', 7, 10);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Charity', 'Dixon', 5, 10);

-- Class 11
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Aleah', 'Bridges', 6, 11);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Logan', 'Mcmahon', 6, 11);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Dane', 'Phillips', 5, 11);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Sienna', 'Sampson', 5, 11);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Reagan', 'Pitts', 6, 11);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Kash', 'Rodriguez', 6, 11);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Issac', 'Horn', 6, 11);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Hailee', 'Patrick', 6, 11);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Elle', 'Sims', 6, 11);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Alonzo', 'Robinson', 6, 11);

-- Class 12
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Tessa', 'Singh', 6, 12);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Kendall', 'Curry', 5, 12);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Marlie', 'Short', 7, 12);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Janessa', 'Morrison', 7, 12);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Jocelyn', 'Butler', 6, 12);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Chaz', 'West', 7, 12);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Terrence', 'Watkins', 6, 12);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Willie', 'Hanson', 7, 12);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Araceli', 'Wyatt', 7, 12);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Marlon', 'Lara', 7, 12);

-- Class 13
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Ethan', 'Johnson', 7, 13);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Parker', 'Mendoza', 6, 13);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Baylee', 'Lewis', 7, 13);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Keshawn', 'Atkinson', 7, 13);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Paula', 'Horton', 5, 13);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Joselyn', 'Fry', 7, 13);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Armani', 'Brennan', 5, 13);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Zaiden', 'Booth', 6, 13);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Dean', 'Whitaker', 5, 13);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Lena', 'Colon', 7, 13);

-- Class 14
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Priscilla', 'Peterson', 5, 14);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Joyce', 'Fitzgerald', 7, 14);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Leandro', 'Jordan', 7, 14);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Warren', 'Caldwell', 7, 14);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Nikhil', 'Foley', 7, 14);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Katie', 'Zimmerman', 7, 14);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Alisson', 'Trevino', 7, 14);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Melanie', 'Lloyd', 5, 14);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Ronnie', 'Logan', 5, 14);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Christopher', 'Mcbride', 5, 14);

-- Class 15
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Cooper', 'Holden', 7, 15);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Kailyn', 'Acevedo', 5, 15);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Ivan', 'Navarro', 5, 15);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Elianna', 'Landry', 7, 15);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Briley', 'Nielsen', 6, 15);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Veronica', 'Andersen', 7, 15);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Maxwell', 'Mccall', 7, 15);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Kaliyah', 'Kline', 5, 15);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Dale', 'Carlson', 6, 15);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Aryanna', 'Duncan', 5, 15);

-- Class 16
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Troy', 'Taylor', 5, 16);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Cristal', 'Haley', 7, 16);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Rene', 'Ramos', 7, 16);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Kymani', 'Neal', 5, 16);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Jean', 'Fields', 5, 16);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Keyla', 'Crawford', 7, 16);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Corinne', 'Edwards', 6, 16);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Maximo', 'Gonzalez', 7, 16);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Billy', 'Bean', 5, 16);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Agustin', 'Gordon', 6, 16);

-- Class 17
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Ashton', 'Beck', 7, 17);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Karley', 'Oneal', 5, 17);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Jaydon', 'Brown', 5, 17);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Keagan', 'Andrews', 7, 17);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Emelia', 'Serrano', 6, 17);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Amari', 'Malone', 5, 17);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Annabelle', 'Lynch', 7, 17);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Jaydin', 'Branch', 7, 17);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Carla', 'Hunter', 7, 17);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Tyshawn', 'Reyes', 7, 17);

-- Class 18
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Adrianna', 'Weaver', 7, 18);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Bria', 'Cain', 5, 18);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Richard', 'Silva', 6, 18);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Warren', 'Shelton', 6, 18);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Kate', 'Burke', 7, 18);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Jaylen', 'Boyd', 6, 18);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Konner', 'Dickson', 7, 18);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Jillian', 'Hobbs', 6, 18);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Jabari', 'Moreno', 7, 18);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Nola', 'Cochran', 7, 18);

-- Class 19
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Trent', 'Villa', 5, 19);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Jaylan', 'Peterson', 6, 19);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Kayla', 'Wong', 6, 19);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Aubree', 'Pitts', 5, 19);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Dayana', 'Paul', 6, 19);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('America', 'Mclaughlin', 7, 19);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Yahir', 'Bentley', 5, 19);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Eliezer', 'Meyer', 6, 19);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Kellen', 'Cortez', 6, 19);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Adrianna', 'Hayden', 6, 19);

-- Class 20
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Jaylee', 'Gross', 7, 20);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Yasmin', 'Cannon', 7, 20);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Marissa', 'Cooke', 5, 20);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Devon', 'Blair', 6, 20);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Jordin', 'Compton', 7, 20);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Aiyana', 'Cain', 5, 20);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Angel', 'Mooney', 7, 20);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Jesus', 'Li', 7, 20);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Cheyenne', 'Huffman', 7, 20);
INSERT INTO CHILD (CHILD_FNAME, CHILD_LNAME, CHILD_AGE, CLASS_ID) VALUES ('Jonathan', 'Molina', 7, 20);