CREATE TABLE CLASSROOM(
	CLASS_ID INTEGER UNSIGNED AUTO_INCREMENT,
    CLASS_CAPACITY INTEGER NOT NULL,
    CLASS_NAME VARCHAR(255) NOT NULL,
    FACILITY_ID INTEGER UNSIGNED,
    PRIMARY KEY (CLASS_ID),
    FOREIGN KEY (FACILITY_ID) REFERENCES FACILITY (FACILITY_ID) ON UPDATE CASCADE
);

SELECT * FROM CLASSROOM;

-- Insert entries for the Math facility
INSERT INTO CLASSROOM (CLASS_CAPACITY, CLASS_NAME, FACILITY_ID) VALUES (10, 'Math Room 1', 1);
INSERT INTO CLASSROOM (CLASS_CAPACITY, CLASS_NAME, FACILITY_ID) VALUES (10, 'Math Room 2', 1);
INSERT INTO CLASSROOM (CLASS_CAPACITY, CLASS_NAME, FACILITY_ID) VALUES (10, 'Math Room 3', 1);
INSERT INTO CLASSROOM (CLASS_CAPACITY, CLASS_NAME, FACILITY_ID) VALUES (10, 'Math Room 4', 1);
INSERT INTO CLASSROOM (CLASS_CAPACITY, CLASS_NAME, FACILITY_ID) VALUES (15, 'Math Room 5', 1);

-- Insert entries for the Science facility
INSERT INTO CLASSROOM (CLASS_CAPACITY, CLASS_NAME, FACILITY_ID) VALUES (10, 'Science Lab 1', 2);
INSERT INTO CLASSROOM (CLASS_CAPACITY, CLASS_NAME, FACILITY_ID) VALUES (10, 'Science Lab 2', 2);
INSERT INTO CLASSROOM (CLASS_CAPACITY, CLASS_NAME, FACILITY_ID) VALUES (10, 'Science Lab 3', 2);
INSERT INTO CLASSROOM (CLASS_CAPACITY, CLASS_NAME, FACILITY_ID) VALUES (10, 'Science Lab 4', 2);
INSERT INTO CLASSROOM (CLASS_CAPACITY, CLASS_NAME, FACILITY_ID) VALUES (18, 'Science Lab 5', 2);

-- Insert entries for the Art facility
INSERT INTO CLASSROOM (CLASS_CAPACITY, CLASS_NAME, FACILITY_ID) VALUES (10, 'Art Studio 1', 3);
INSERT INTO CLASSROOM (CLASS_CAPACITY, CLASS_NAME, FACILITY_ID) VALUES (10, 'Art Studio 2', 3);
INSERT INTO CLASSROOM (CLASS_CAPACITY, CLASS_NAME, FACILITY_ID) VALUES (10, 'Art Studio 3', 3);
INSERT INTO CLASSROOM (CLASS_CAPACITY, CLASS_NAME, FACILITY_ID) VALUES (10, 'Art Studio 4', 3);
INSERT INTO CLASSROOM (CLASS_CAPACITY, CLASS_NAME, FACILITY_ID) VALUES (20, 'Art Studio 5', 3);

-- Insert entries for the Language facility
INSERT INTO CLASSROOM (CLASS_CAPACITY, CLASS_NAME, FACILITY_ID) VALUES (10, 'Language Lab 1', 4);
INSERT INTO CLASSROOM (CLASS_CAPACITY, CLASS_NAME, FACILITY_ID) VALUES (10, 'Language Lab 2', 4);
INSERT INTO CLASSROOM (CLASS_CAPACITY, CLASS_NAME, FACILITY_ID) VALUES (10, 'Language Lab 3', 4);
INSERT INTO CLASSROOM (CLASS_CAPACITY, CLASS_NAME, FACILITY_ID) VALUES (10, 'Language Lab 4', 4);
INSERT INTO CLASSROOM (CLASS_CAPACITY, CLASS_NAME, FACILITY_ID) VALUES (25, 'Language Lab 5', 4);