CREATE TABLE IF NOT EXISTS FACILITY(
	FACILITY_ID INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    FACILITY_NAME VARCHAR(255) NOT NULL
);

SELECT * FROM FACILITY;

INSERT INTO FACILITY (FACILITY_NAME) VALUES ('Math');
INSERT INTO FACILITY (FACILITY_NAME) VALUES ('Science');
INSERT INTO FACILITY (FACILITY_NAME) VALUES ('Art');
INSERT INTO FACILITY (FACILITY_NAME) VALUES ('Language');
