CREATE TABLE TEACHER(
	TEACHER_ID INTEGER UNSIGNED AUTO_INCREMENT,
    TEACHER_FNAME VARCHAR(255) NOT NULL,
    TEACHER_LNAME VARCHAR(255) NOT NULL,
    CLASS_ID INTEGER UNSIGNED,
    PRIMARY KEY (TEACHER_ID),
    FOREIGN KEY (CLASS_ID) REFERENCES CLASSROOM (CLASS_ID) ON UPDATE CASCADE
);

SELECT * FROM TEACHER;

INSERT INTO TEACHER (TEACHER_FNAME, TEACHER_LNAME, CLASS_ID) VALUES ('John', 'Smith', 1);
INSERT INTO TEACHER (TEACHER_FNAME, TEACHER_LNAME, CLASS_ID) VALUES ('Alice', 'Johnson', 2);
INSERT INTO TEACHER (TEACHER_FNAME, TEACHER_LNAME, CLASS_ID) VALUES ('Michael', 'Williams', 3);
INSERT INTO TEACHER (TEACHER_FNAME, TEACHER_LNAME, CLASS_ID) VALUES ('Emily', 'Brown', 4);
INSERT INTO TEACHER (TEACHER_FNAME, TEACHER_LNAME, CLASS_ID) VALUES ('Daniel', 'Jones', 5);
INSERT INTO TEACHER (TEACHER_FNAME, TEACHER_LNAME, CLASS_ID) VALUES ('Sarah', 'Davis', 6);
INSERT INTO TEACHER (TEACHER_FNAME, TEACHER_LNAME, CLASS_ID) VALUES ('David', 'Miller', 7);
INSERT INTO TEACHER (TEACHER_FNAME, TEACHER_LNAME, CLASS_ID) VALUES ('Jessica', 'Wilson', 8);
INSERT INTO TEACHER (TEACHER_FNAME, TEACHER_LNAME, CLASS_ID) VALUES ('Matthew', 'Taylor', 9);
INSERT INTO TEACHER (TEACHER_FNAME, TEACHER_LNAME, CLASS_ID) VALUES ('Emma', 'Martinez', 10);
INSERT INTO TEACHER (TEACHER_FNAME, TEACHER_LNAME, CLASS_ID) VALUES ('Christopher', 'Anderson', 11);
INSERT INTO TEACHER (TEACHER_FNAME, TEACHER_LNAME, CLASS_ID) VALUES ('Olivia', 'Hernandez', 12);
INSERT INTO TEACHER (TEACHER_FNAME, TEACHER_LNAME, CLASS_ID) VALUES ('Andrew', 'Garcia', 13);
INSERT INTO TEACHER (TEACHER_FNAME, TEACHER_LNAME, CLASS_ID) VALUES ('Elizabeth', 'Lopez', 14);
INSERT INTO TEACHER (TEACHER_FNAME, TEACHER_LNAME, CLASS_ID) VALUES ('Ryan', 'Young', 15);
INSERT INTO TEACHER (TEACHER_FNAME, TEACHER_LNAME, CLASS_ID) VALUES ('Grace', 'Scott', 16);
INSERT INTO TEACHER (TEACHER_FNAME, TEACHER_LNAME, CLASS_ID) VALUES ('Joshua', 'Green', 17);
INSERT INTO TEACHER (TEACHER_FNAME, TEACHER_LNAME, CLASS_ID) VALUES ('Ava', 'Adams', 18);
INSERT INTO TEACHER (TEACHER_FNAME, TEACHER_LNAME, CLASS_ID) VALUES ('Kevin', 'King', 19);
INSERT INTO TEACHER (TEACHER_FNAME, TEACHER_LNAME, CLASS_ID) VALUES ('Sophia', 'Hill', 20);